EXPERIMENT:
  COMPILE: false
SIMULATION:
  TREE: SimuEvol/data/trees/placnr.lht.rootedtree.nhx
  PREFERENCES: SimuEvol/data/preferences/np_5000_498.prefs
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  ROOT_AGE: 150e6
  GENERATION_TIME: 5
  EXON_SIZE: 300
  SEED: 65489
  BRANCH_WISE_CORRELATION: false
  FIXED_POP_SIZES: false
  FIXED_MUT_RATE: false
  FIXED_GENERATION_TIME: false
SimuFold:
  PDB_FOLDER: SimuEvol/data/pdbfiles
  NBR_EXONS: 16
  NBR_GRID_STEP: 100
  POP_SIZE: 1e5
  CUT_OFF: 7.0
SimuDiv:
  BETA: 1.0
  NBR_GRID_STEP: 100
SimuPoly:
  BETA: 1.0
  POP_SIZE: 5000
  SAMPLE_SIZE: 20
  NOISE_SIGMA: 0.2
  NOISE_THETA: 0.5
SimuGeo:
  NBR_GRID_STEP: 100
  POP_SIZE: 200.0
  COMPLEXITY: 3
  NBR_EXONS: 16
INFERENCE_REPLICATE:
  CHAINS: [1, 2]
  POLYMORPHISM: [false]
  MODELS: [node, aa, nodeomega]
  SIMULATORS: [SimuDiv, SimuFold, SimuGeo, SimuPoly]
INFERENCE:
  RESTART: false
  POINTS: 4000
  PRECISION: 10
  NCAT: 50
INFERENCE_NODE:
  TRAITS: false
  FOSSILS: 0
  MOVE_ROOT_POP_SIZE: false
  CLAMP_PREFERENCES: false
  CLAMP_POP_SIZES: false
  CLAMP_NUC_MATRIX: false
  CLAMP_CORR_MATRIX: false
  ARITHMETIC: false
  DOF: 1
PLOT:
  BURN_IN: 1000
