EXPERIMENT:
  COMPILE: false
SIMULATION:
  TREE: SimuEvol/data/trees/placnr.short.rootedtree.nhx
  PREFERENCES: SimuEvol/data/preferences/np_5000_30.prefs
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  ROOT_AGE: 300e6
  GENERATION_TIME: 10
  EXON_SIZE: 300
  SEED: 653
  BRANCH_WISE_CORRELATION: false
  FIXED_POP_SIZES: false
  FIXED_MUT_RATE: false
  FIXED_GENERATION_TIME: false
SimuFold:
  PDB_FOLDER: SimuEvol/data/pdbfiles
  NBR_EXONS: 12
  NBR_GRID_STEP: 100
  POP_SIZE: 1e5
  CUT_OFF: 7.0
SimuGeo:
  NBR_GRID_STEP: 100
  POP_SIZE: 2000.0
  COMPLEXITY: 3
  NBR_EXONS: 12
SimuDiv:
  BETA: 1.0
  NBR_GRID_STEP: 100
SimuPoly:
  BETA: 1.0
  POP_SIZE: 5000
  SAMPLE_SIZE: 20
  NOISE_SIGMA: 0.0
  NOISE_THETA: 0.9
INFERENCE_REPLICATE:
  CHAINS: [1, 2]
  POLYMORPHISM: [false]
  MODELS: [node]
  SIMULATORS: [SimuDiv, SimuFold, SimuGeo, SimuPoly]
INFERENCE:
  RESTART: false
  POINTS: 3000
  PRECISION: 10
  NCAT: 50
INFERENCE_NODE:
  TRAITS: true
  FOSSILS: 0
  MOVE_ROOT_POP_SIZE: false
  CLAMP_PREFERENCES: false
  CLAMP_POP_SIZES: false
  CLAMP_NUC_MATRIX: false
  CLAMP_CORR_MATRIX: false
  ARITHMETIC: false
PLOT:
  BURN_IN: 200
