INFERENCE_REPLICATE:
  CHAINS: [1, 2]
  MODELS: [node, aa, nodeomega]
  POLYMORPHISM: [false]
INFERENCE:
  RESTART: true
  POINTS: 4000
  PRECISION: 12
  NCAT: 50
INFERENCE_NODE:
  MOVE_ROOT_POP_SIZE: false
  CLAMP_POP_SIZES: false
  CLAMP_NUC_MATRIX: false
  CLAMP_CORR_MATRIX: false
  ARITHMETIC: false
PLOT:
  BURN_IN: 1000
